services:
  app:
    build:
      context: .
    container_name: kanban_backend
    restart: unless-stopped
    ports:
      - "${PORT}:${PORT}" 
    env_file:
      - .env
    volumes:
      - .:/app 
      - /app/node_modules 
    command: npm run start:dev
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: redis:7.0
    container_name: kanban_backend_redis
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
